### ISSUE TITLE
LSF cluster usage

### ISSUE THREAD

**Issue by TnakaNY** [GooglingTheCancerGenome/sv-callers#48]
HI,
Could you provide example command to submit a job to LSF cluster? 
I am not a specialist for job scheduler.

Thanks.

**Comment by arnikz** [comment]
Hi,

Sorry, I don't have access to test on a LSF cluster. Use the [`bsub`](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_command_ref/bsub.man_top.1.html) command directly rather than [`xenon`](https://www.research-software.nl/software/xenon-cli) (LSF is not supported yet).

Something like:
```
SUBMIT_CMD="bsub \
-J smk.{rule} \
-cwd \
-T {threads} \
-W 15 \
-M {resources.mem_mb} \
-o stdout-%J.log \
-e stderr-%J.log"
```
`snakemake --use-conda --cluster "${SUBMIT_CMD}"...` (see [README](/GooglingTheCancerGenome/sv-callers/blob/master/README.md) and [this](https://blog.esciencecenter.nl/portable-hpc-workflows-with-snakemake-and-xenon-e971e5127391) blog).

Cheers,
 Arnold

**Comment by TnakaNY** [comment]
I see. Thank you for quick reply!

**Comment by jmaassen** [comment]
We could add LSF to xenon provided we find a way to properly test it (preferably using an LSF docker image).

**Comment by xiaojingshi** [comment]
> I see. Thank you for quick reply!

Hi, will you be able to share your command to submit a job to LSF cluster? Thank you very much.
