### ISSUE TITLE
gridss error while running with sv-callers

### ISSUE THREAD

**Issue by nitha26** [GooglingTheCancerGenome/sv-callers#58]
Hi @arnikz ,

I tried running sv-callers for NA12878 to call Germline SVs but I got an error while executing gridss module. I tried many times, and finally I ran  sv-callers for this particular sample with  only  gridss module with enough memory, but still generating error while generating gridss output.  Could you point out why this error occurred? 

The log file greater than 10MB, so I had attached only error details in a file. Kindly, look into this and provide the solution.
Thank you!
[error_detailsNA12878.txt](https://github.com/GooglingTheCancerGenome/sv-callers/files/6065756/error_detailsNA12878.txt

**Comment by arnikz** [comment]
The issue stems from using the NA12878 sample (BAM) with the GRCh38 rather than with the GRCh37 reference (FASTA). I recall the same issue with the GRIDSS version used in the past. My suggestion is to a) analyze the sample with the corresponding reference (as done in [this](https://doi.org/10.5281/zenodo.3526703) benchmark dataset), b) re-align the reads against the newer reference genome yourself or c) use a more recent GRIDSS (N.B.: it hasn't been tested in the _sv-callers_; see #35).

**Comment by nitha26** [comment]
Thank you very much for your reply. But this NA12878 is cell-line sample
was sequenced by our lab recently and aligned with GRCh38.  I was thinking, why
only for this particular sample I was getting error while running gridss
other tools like manta and lumpy was able to provide vcf files.  I was able
to run same sample separately in Delly2 8.5 without error.  I will try to
run in latest version.  Thank you.
